### ISSUE TITLE
Build OAuth2 service w/ JWT for Data Portal authorization

### ISSUE THREAD

**Issue by Fgerthoffert** [kids-first/kf-auth-service#2]
# Technical Stack
## Language and Frameworks
* Java 8
* Lombok
* Spring Boot https://projects.spring.io/spring-boot/
* Spring Security
## Build Tools & CI
* Maven 3.5.0+ 
* TravisCI

## Data Store
* MongoDB or PostreSQL - I'm open to either

## Tasks
- [x] An OAuth Server
- [x] User management APIs
- [x] Swagger Docs
- [x] API endpoints to exchange and verify ID JWT with EGO auth JWTs.
- [x] Enable authorization with JWTs
 
## Comments
***Java 9*** is something I'm looking at closely but after the talk with the Elasticsearch engineers at Elastic{ON} in Toronto, my confidence was shaken in the new garbage collector. Also lombok support is a blocking feature, as I'd rather have lombok than Java 9.

**Comment by andricDu** [comment]
@ra-ver and I will be working through some PoCs regarding this. 

The main priority is to get the OAuth2 w/ JWTs done correctly. Once that is done, adding additional OpenID Connect providers will be trivial.

**Comment by andricDu** [comment]
# Technical Stack
## Language and Frameworks
* Java 8
* Lombok
* Spring Boot https://projects.spring.io/spring-boot/
* Spring Security
## Build Tools & CI
* Maven 3.5.0+ 
* TravisCI

## Data Store
* MongoDB or PostreSQL - I'm open to either

## Comments
***Java 9*** is something I'm looking at closely but after the talk with the Elasticsearch engineers at Elastic{ON} in Toronto, my confidence was shaken in the new garbage collector. Also lombok support is a blocking feature, as I'd rather have lombok than Java 9.

**Comment by andricDu** [comment]
We are going to go with PostgeSQL as we can then leverage Amazon RDS which will improve scalability, management overhead, and is HIPAA eligible
